### ISSUE TITLE
Move the meeting minutes to the wiki

### ISSUE THREAD

**Issue by UO258418** [Arquisoft/dechat_en3b#13]
Issues are supposed to be dynamic tasks that are open to indicate theres something to be done, and once complete they should be closed

**Comment by danivilla9** [comment]
Meeting minutes are already moved. When I write the minute from the last meeting (Juan was not able to do so because of its illness) and update the label guide, I'll close this issue.

I'll probably open other issue for moving the attachments / requirements update.

**Comment by danivilla9** [comment]
Meeting 7 is written in the wiki. By the time being we'll keep attachments / requirements update in the issues, but they will probably have to be moved to the wiki at some point.
