### ISSUE TITLE
Meeting Minute 2

### ISSUE THREAD

**Issue by UO252376** [Arquisoft/dechat_en3b#2]
Topic: Documentation
Date: 7/2/2019
Participants: Nicolás Mencía, Juan Sánchez-Ocaña, David González, Jonás Martínez and Daniel Villanueva.
Objectives: Assign documentation files 1-4. Discuss Arc_42 syntax.

* All programmers should do the SOLID tutorial (https://solid.inrupt.com/docs/app-on-your-lunch-break)
* The project will be developed in JavaScript. Each programmer will be in charge of the documentation of their own code. 
* The general documentation will be divided. Discuss who's in charge of organizing the docs.
* Write documentation using AsciiDoc.
* Current best option or the data storage is JSON. Review.

Due to next week:
* Introduction and goals (intro and requirements): @uo251480 
* Introduction and goals (quality and stakeholders): @UO258418 
* Architecture constraints: @UO252376 
* System scope and context: @nicomencia 
* Solution Strategy: @danivilla9 

This documents should be updated with the new concrete knowledge gained during the course.
@uo251480  will be in charge of the next meeting minute.

**Comment by danivilla9** [comment]
Moved to the Wiki.
