### ISSUE TITLE
Deploy application in GitHub pages

### ISSUE THREAD

**Issue by danivilla9** [Arquisoft/dechat_en3b#25]
Labra has stated that the application and the documentation have to be deployed in GitHub pages, and also that the app has to include a link to the documentation in it. We can follow a guide from Angular that he has linked here: https://angular.io/guide/deployment#deploy-to-github-pages

- [x] Deploy application in [this link](https://arquisoft.github.io/dechat_en3b/)
- [x] Deploy documentation in [this link](https://arquisoft.github.io/dechat_en3b/docs)
- [x] Link documentation from the application

**Comment by uo251480** [comment]
This is already done
