### ISSUE TITLE
Meeting Minute 3

### ISSUE THREAD

**Issue by uo251480** [Arquisoft/dechat_en3b#3]
Topic: Structure of our app.
Date: 14/2/2019
Participants: Nicolás Mencía, Juan Sánchez-Ocaña, David González, Jonás Martínez and Daniel Villanueva.
Objectives: Discuss about how to implement the solution.

* Every member should get familiar with RDF's syntax.
* Create a [prototype of a possible starter architecture.](https://github.com/Arquisoft/dechat_en3b/issues/4)
* Look for structures to store the data on the PODs.

Due to next week:

* @UO252376 is going to make the first prototype of the application interface.
* Discuss some behavior of our chat (what will happen when the PODs are turned of, when one of them is removed...)
* Continue with the documentation. (At least) The four documentation's topics should be fully covered up to this point.
* Make a skeleton of our app to discuss it next week.

@nicomencia will be in charge of the next meeting minute.

**Comment by danivilla9** [comment]
Moved to the Wiki.
