### ISSUE TITLE
Meeting Minute 4

### ISSUE THREAD

**Issue by nicomencia** [Arquisoft/dechat_en3b#7]
Topic: Structure of our app.
Date: 21/2/2019
Participants: Nicolás Mencía, Juan Sánchez-Ocaña, David González, Jonás Martínez and Daniel Villanueva.
Objectives: 

* Fix and create the index.html with all the documentation.
* Add user HTML interface prototype 

Due to next week:

* Change/simplify some parts of the documentation and clean it
* Install maven and learn how to generate the documentation in HTML
* Generate a script in order to do an automatic documentation generation
* Part 5 'Design decisions' make the documentation

@UO258418  will be in charge of the next meeting minute.

**Comment by danivilla9** [comment]
Moved to the Wiki
