### ISSUE TITLE
Meeting Minute 5

### ISSUE THREAD

**Issue by UO258418** [Arquisoft/dechat_en3b#9]
Topic: Change project from maven to npm (node.js)
Date: 28/2/19
Participants: Daniel Villanueva, Juan Sánchez-Ocaña and Jonás Martínez
Objectives:
* Change the project structure to work with node.js
* Try the solid-auth-client module

Due to next week:
* Design the login window
* Create some tests
* Study RTC technology to get confortable with it

@danivilla9 will be in charge of the next meeting minute

**Comment by danivilla9** [comment]
Moved to the Wiki.
